version: '3'
services: 
    db:
        container_name: postgres
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: ngFinances
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
    
    app:
        container_name: ng-finance
        restart: always
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db