version: '3'
services: 
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 12345678
        ports:
            - "5432:5432"
        container_name: db

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: 'db'
            DB_PORT: 5432
            DB_USER: 'postgres'
            DB_PASS: 12345678
            DB_NAME: 'postgres'
        ports:
            - "3000:3000"
        container_name: ng-finance
        depends_on:
            - db
