version: '3'
services: 
        
    db:
        container_name: postgres
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./pgdata:/data/postgres
        ports:
            - "5432:5432"
        restart: always

    app:
        container_name: ng-finance
        restart: always
        build: .
        ports:
            - "3000:3000"
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
        depends_on:
            - db
        volumes:
            - './:/usr/src'
        links:
            - db
