version: '3'
services: 
        
    db:
        container_name: postgres
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./pgdata:/data/postgres
        ports:
            - "5432:5432"
        restart: always